function displayRecipe(response)
{
    new Typewriter("#recipe", {
        strings: response.data.answer,
        autoStart: true,
        delay: 1,
        cursor: "",
      });
}

function generateRecipe(event) 
{
event.preventDefault();
let instructionInput = document.querySelector("#user-input");
let apiKey = "14cfdda3fo2fca08bfa9c4f19a5dat70";
let context = "You are a cookery expert and the mission is to generate a recipe and instructions based on the user request in basic HTML and separate each line with a <br />. Make sure to follow the user instructions. Do not include a title to the recipe Sign the recipe with 'Recipe Generated by SheCodes AI' inside a <strong> element at the end of the poem and NOT at the beginning";
let prompt = `Generate recipe instructions ${instructionInput.value}`;
let apiUrl = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;

axios.get(apiUrl).then(displayRecipe);


}

let recipeGeneratorElement = document.querySelector("#recipe-generator");
recipeGeneratorElement.addEventListener("submit", generateRecipe)